name: Exercise tests

on: [push]

jobs:
  test-lab1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
      working-directory: ./lab1
    - name: Run test examples
      run: cd lab1 && bash evaluate.sh
      shell: bash

  test-lab2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
      working-directory: ./lab2
    - name: Run test examples
      run: cd lab2 && bash evaluate.sh
      shell: bash

  test-lab3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
      working-directory: ./lab3
    - name: Run test examples
      run: cd lab3 && bash evaluate.sh
      shell: bash

  test-lab4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
      working-directory: ./lab4
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install FRISCjs
      run: npm install friscjs
      shell: bash
    - name: Run test examples
      run: cd lab4 && bash evaluate.sh
      shell: bash
